### ISSUE TITLE
Push practice/1 branch

### ISSUE THREAD

**Issue by dtothefp** [kentcdodds/random-user-coverage#1]
hey @kentcdodds nice tutorial https://www.youtube.com/watch?v=P-1ZZkpEmQA. Wondering if you could push the `practice/1` branch. Also, a useful addition to this tutorial would be debugging in Karma with sourcemap support.

**Comment by kentcdodds** [comment]
I'm so sorry. It looks like I've removed the repo locally and therefore
what you see is what you get in that repo. :-( I'm sorry for that brainless
action :-/ I hope the video is helpful enough. Also, check this out
https://github.com/kentcdodds/kcd-common-tools.

-Kent C. Dodds

On Sun, Jul 12, 2015 at 11:28 AM, David Fox-Powell <notifications@github.com

**Comment by dtothefp** [comment]
Yeh, I checked out that repo. Like what you did with the different webpack config functions. I have a sample repo here that I'm going to implement your Karma stuff into. You might like some of the gulp/es6 stuff in there for automation of tasks.

https://github.com/dtothefp/browserstack-webdriverio-e2e

**Comment by kentcdodds** [comment]
Cool stuff! I'll have to give that a look when I finally get into browserstack :-)
